name: test-binder-sage

channels:
  - defaults
  - conda-forge

dependencies:
  - sage=9.2
    # ipywidgets is a Sage dependency, but rendering fails in binder
    # presumably some extension activation missing.
    # https://discourse.jupyter.org/t/binder-and-sagemath/11059/8
  - ipywidgets
